### ISSUE TITLE
rumprun user apps not worked correctly

### ISSUE THREAD

**Issue by mohamadrezashafie** [seL4/camkes-manifest#5]
hi. 
i'm recently worked on sel4 with camkes framework. when i compile rumprun_hello on x86_64 platform its compiled and build correctly but when run with qemu by ./simulate script, program crashed with this errors: 
**simple_get_extended_bootinfo_length@simple.h:600 simple_get_extended_bootinfo_length not implemented
FAULT HANDLER: data fault from hello.hello_0_control (ID 0x1) on address 0x8, pc = 0x402b7f, fsr = 0x6
FAULT HANDLER: Register dump:
FAULT HANDLER: rip	:0x402b7f**

so i found that this method not supported yet so i return 0 in this method
for second problem that cause failure if trace program and i found that in "init rumprun" process the program failed in the /projects/sel4runtime/include/sel4_arch/x86_64/sel4runtime/thread_arch.h file and  sel4runtime_set_tls_base method. 
so i read git log and in recently commit your team use sel4runtime for thread management, so when running rumprun_hello we crashed in that versioin. can you help me fix this bug???? thanks for your attention.

**Comment by xurtis** [comment]
The tools that we depend on to [build rumprun applications](https://github.com/rumpkernel/buildrump.sh/tree/master) haven't been maintained in the last 4 years and have an issue in the linking process that prevents the layout of thread-local-storage (TLS) being correctly determined by the runtime. As the libsel4 and the runtime now depend on correctly functioning TLS they cannot be used from rumprun given its current configuration. Given this situation, we are not currently supporting rumprun from within CAmkES.

**Comment by kent-mcleod** [comment]
The fault was being caused by seL4rumtime having an incorrect view of the TLS region due to a CAmkES linker script setting the values of _tbss/_tdata start and end symbols too early in the linking process.  This should be resolved by: https://github.com/seL4/camkes-tool/pull/41

**Comment by mohamadrezashafie** [comment]
its resolvedm successfully.this commit saved my time :)
Thanks a lot for your help.

On Sun, 06/09/2020 12:30 PM, Kent McLeod <notifications@github.com> wrote:
> 
The fault was being caused by seL4rumtime having an incorrect view of the TLS region due to a CAmkES linker script setting the values of _tbss/_tdata start and end symbols too early in the linking process.  This should be resolved by: seL4/camkes-tool#41
—
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
This email was Anti Virus checked by  Security Gateway.

**Comment by mincheolsung** [comment]
I tried to run rumprun_hello with camkes but the rumprun crashed with errors:

simple_get_extended_bootinfo_length@simple.h:608 simple_get_extended_bootinfo_length not implemented
vka_cspace_alloc@vka.h:149 Unimplemented
vka_alloc_object_at_maybe_dev@object.h:47 Failed to allocate cslot: error -1
init_rumprun@entry.c:306 [Cond failed: res != 0]
	Failed to allocate notification object

I confirmed that this patch (https://github.com/seL4/camkes-tool/pull/41) was applied in my camkes-tool.
Can anyone help me?

**Comment by Lahiru-Dissanayake** [comment]
> I tried to run rumprun_hello with camkes but the rumprun crashed with errors:
> 
> [simple_get_extended_bootinfo_length@simple.h](mailto:simple_get_extended_bootinfo_length@simple.h):608 simple_get_extended_bootinfo_length not implemented [vka_cspace_alloc@vka.h](mailto:vka_cspace_alloc@vka.h):149 Unimplemented [vka_alloc_object_at_maybe_dev@object.h](mailto:vka_alloc_object_at_maybe_dev@object.h):47 Failed to allocate cslot: error -1 [init_rumprun@entry.c](mailto:init_rumprun@entry.c):306 [Cond failed: res != 0] Failed to allocate notification object
> 
> I confirmed that this patch ([seL4/camkes-tool#41](https://github.com/seL4/camkes-tool/pull/41)) was applied in my camkes-tool. Can anyone help me?

Did you find a solution for this problem?

**Comment by dinukaamarasinghe817** [comment]
> I tried to run rumprun_hello with camkes but the rumprun crashed with errors:
> 
> [simple_get_extended_bootinfo_length@simple.h](mailto:simple_get_extended_bootinfo_length@simple.h):608 simple_get_extended_bootinfo_length not implemented [vka_cspace_alloc@vka.h](mailto:vka_cspace_alloc@vka.h):149 Unimplemented [vka_alloc_object_at_maybe_dev@object.h](mailto:vka_alloc_object_at_maybe_dev@object.h):47 Failed to allocate cslot: error -1 [init_rumprun@entry.c](mailto:init_rumprun@entry.c):306 [Cond failed: res != 0] Failed to allocate notification object
> 
> I confirmed that this patch ([seL4/camkes-tool#41](https://github.com/seL4/camkes-tool/pull/41)) was applied in my camkes-tool. Can anyone help me?

Did you find any solutions to this?

**Comment by dinukaamarasinghe817** [comment]
> The fault was being caused by seL4rumtime having an incorrect view of the TLS region due to a CAmkES linker script setting the values of _tbss/_tdata start and end symbols too early in the linking process. This should be resolved by: [seL4/camkes-tool#41](https://github.com/seL4/camkes-tool/pull/41)

The issue seems to be still persist somehow. How can I make this work? any suggestions? Will checking out older versions of the repository solve this problem?

**Comment by dinukaamarasinghe817** [comment]
> its resolvedm successfully.this commit saved my time :)
> Thanks a lot for your help.
> On Sun, 06/09/2020 12:30 PM, Kent McLeod ***@***.***> wrote:
> The fault was being caused by seL4rumtime having an incorrect view of the TLS region due to a CAmkES linker script setting the values of _tbss/_tdata start and end symbols too early in the linking process.  This should be resolved by: [seL4/camkes-tool#41](https://github.com/seL4/camkes-tool/pull/41)
> —
>  You are receiving this because you authored the thread.
>  Reply to this email directly, view it on GitHub, or unsubscribe.
> -- 
> This email was Anti Virus checked by  Security Gateway.

How did you manage to solve the issue? For me the issue still persist. It seems like the above mentioned TLS fix in the `camkes-tools` repository did not solve the problem.
